/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as GateRouteImport } from './routes/gate'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBoardRouteImport } from './routes/app/board'
import { Route as AppBoxRouteImport } from './routes/app/box'
import { Route as AppCrewRouteImport } from './routes/app/crew'
import { Route as AppDispatchRouteImport } from './routes/app/dispatch'
import { Route as AppFleetRouteImport } from './routes/app/fleet'
import { Route as AppLockerRouteImport } from './routes/app/locker'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppMoneyRouteImport } from './routes/app/money'
import { Route as AppOwnerRouteImport } from './routes/app/owner'
import { Route as AppPhoneRouteImport } from './routes/app/phone'
import { Route as AppShopRouteImport } from './routes/app/shop'
import { Route as AppTodayRouteImport } from './routes/app/today'
import { Route as AppTrackRouteImport } from './routes/app/track'
import { Route as PortalShipperRouteImport } from './routes/portal.$shipper'
import { Route as TrackCodeRouteImport } from './routes/track.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppBoxRoute = AppBoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewRoute = AppCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppLockerRoute = AppLockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppPhoneRoute = AppPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const PortalShipperRoute = PortalShipperRouteImport.update({
  id: '/portal/$shipper',
  path: '/portal/$shipper',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/gate': typeof GateRoute
  '/app/board': typeof AppBoardRoute
  '/app/box': typeof AppBoxRoute
  '/app/crew': typeof AppCrewRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/locker': typeof AppLockerRoute
  '/app/logs': typeof AppLogsRoute
  '/app/money': typeof AppMoneyRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/phone': typeof AppPhoneRoute
  '/app/shop': typeof AppShopRoute
  '/app/today': typeof AppTodayRoute
  '/app/track': typeof AppTrackRoute
  '/portal/$shipper': typeof PortalShipperRoute
  '/track/$code': typeof TrackCodeRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gate': typeof GateRoute
  '/app/board': typeof AppBoardRoute
  '/app/box': typeof AppBoxRoute
  '/app/crew': typeof AppCrewRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/locker': typeof AppLockerRoute
  '/app/logs': typeof AppLogsRoute
  '/app/money': typeof AppMoneyRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/phone': typeof AppPhoneRoute
  '/app/shop': typeof AppShopRoute
  '/app/today': typeof AppTodayRoute
  '/app/track': typeof AppTrackRoute
  '/portal/$shipper': typeof PortalShipperRoute
  '/track/$code': typeof TrackCodeRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/gate': typeof GateRoute
  '/app/board': typeof AppBoardRoute
  '/app/box': typeof AppBoxRoute
  '/app/crew': typeof AppCrewRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/locker': typeof AppLockerRoute
  '/app/logs': typeof AppLogsRoute
  '/app/money': typeof AppMoneyRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/phone': typeof AppPhoneRoute
  '/app/shop': typeof AppShopRoute
  '/app/today': typeof AppTodayRoute
  '/app/track': typeof AppTrackRoute
  '/portal/$shipper': typeof PortalShipperRoute
  '/track/$code': typeof TrackCodeRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/gate'
    | '/app/board'
    | '/app/box'
    | '/app/crew'
    | '/app/dispatch'
    | '/app/fleet'
    | '/app/locker'
    | '/app/logs'
    | '/app/money'
    | '/app/owner'
    | '/app/phone'
    | '/app/shop'
    | '/app/today'
    | '/app/track'
    | '/portal/$shipper'
    | '/track/$code'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gate'
    | '/app/board'
    | '/app/box'
    | '/app/crew'
    | '/app/dispatch'
    | '/app/fleet'
    | '/app/locker'
    | '/app/logs'
    | '/app/money'
    | '/app/owner'
    | '/app/phone'
    | '/app/shop'
    | '/app/today'
    | '/app/track'
    | '/portal/$shipper'
    | '/track/$code'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/gate'
    | '/app/board'
    | '/app/box'
    | '/app/crew'
    | '/app/dispatch'
    | '/app/fleet'
    | '/app/locker'
    | '/app/logs'
    | '/app/money'
    | '/app/owner'
    | '/app/phone'
    | '/app/shop'
    | '/app/today'
    | '/app/track'
    | '/portal/$shipper'
    | '/track/$code'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GateRoute: typeof GateRoute
  PortalShipperRoute: typeof PortalShipperRoute
  TrackCodeRoute: typeof TrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/box': {
      id: '/app/box'
      path: '/box'
      fullPath: '/app/box'
      preLoaderRoute: typeof AppBoxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crew': {
      id: '/app/crew'
      path: '/crew'
      fullPath: '/app/crew'
      preLoaderRoute: typeof AppCrewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fleet': {
      id: '/app/fleet'
      path: '/fleet'
      fullPath: '/app/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locker': {
      id: '/app/locker'
      path: '/locker'
      fullPath: '/app/locker'
      preLoaderRoute: typeof AppLockerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/money': {
      id: '/app/money'
      path: '/money'
      fullPath: '/app/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/phone': {
      id: '/app/phone'
      path: '/phone'
      fullPath: '/app/phone'
      preLoaderRoute: typeof AppPhoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/track': {
      id: '/app/track'
      path: '/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$shipper': {
      id: '/portal/$shipper'
      path: '/portal/$shipper'
      fullPath: '/portal/$shipper'
      preLoaderRoute: typeof PortalShipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppBoxRoute: typeof AppBoxRoute
  AppCrewRoute: typeof AppCrewRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppFleetRoute: typeof AppFleetRoute
  AppLockerRoute: typeof AppLockerRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppPhoneRoute: typeof AppPhoneRoute
  AppShopRoute: typeof AppShopRoute
  AppTodayRoute: typeof AppTodayRoute
  AppTrackRoute: typeof AppTrackRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppBoxRoute: AppBoxRoute,
  AppCrewRoute: AppCrewRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppFleetRoute: AppFleetRoute,
  AppLockerRoute: AppLockerRoute,
  AppLogsRoute: AppLogsRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppPhoneRoute: AppPhoneRoute,
  AppShopRoute: AppShopRoute,
  AppTodayRoute: AppTodayRoute,
  AppTrackRoute: AppTrackRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GateRoute: GateRoute,
  PortalShipperRoute: PortalShipperRoute,
  TrackCodeRoute: TrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
